---
name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run build
      
      # - name: Save build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: contract-artifacts
      #     path: |
      #       artifacts
      #       cache/*.json


  # test-hardhat:
  #   name: Hardhat Test
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs:
  #     - build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install modules
  #       run: npm install

  #     # - name: Load build artifacts
  #     #   uses: actions/download-artifact@v3
  #     #   with:
  #     #     name: contract-artifacts

  #     - name: Test
  #       run: npm run test:hardhat


  # test-forge:
  #   name: Forge Test
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs:
  #     - build
  #   steps:
  #     - uses: actions/checkout@v3

  #     # Forge needs node_modules/
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install modules
  #       run: npm install

  #     - name: Install Foundry
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: nightly

  #     - name: Run Forge build
  #       run: |
  #         forge --version
  #         forge build

  #     - name: Run Forge tests
  #       run: |
  #         forge test -vvv


  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   needs:
  #     - build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install modules
  #       run: npm install

  #     - name: Lint
  #       run: npm run lint:check


  # contracts-size:
  #   name: Contracts Size
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   needs:
  #     - build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install modules
  #       run: npm install

  #     # - name: Load build artifacts
  #     #   uses: actions/download-artifact@v3
  #     #   with:
  #     #     name: contract-artifacts

  #     - name: Check sizes
  #       run: npm run check-size


  # approve-test-bsc:
  #   name: Approve Test BSC
  #   runs-on: ubuntu-latest
  #   needs:
  #     - test-hardhat
  #     - test-forge
  #     - lint
  #     - contracts-size
  #   steps:
  #     - name: manual approve
  #       run: echo "Manually approved"


  # approve-test-polygon:
  #   name: Approve Test Polygon
  #   runs-on: ubuntu-latest
  #   needs:
  #     - test-hardhat
  #     - test-forge
  #     - lint
  #     - contracts-size
  #   steps:
  #     - name: manual approve
  #       run: echo "Manually approved"


  deploy-test-bsc:
    name: Deploy Test BSC
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: test-bsc
    needs:
      - build
    steps:
      - name: Echo begin
        run: echo "Fucking test"

      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Install modules
      #   run: npm install

      - name: Echo end
        run: echo "Fucking test"
